from . import class_widget_model
from . import content_widget_model
from . import content_widget_random_model
from . import htmlbox_widget_model
from . import picbox_widget_model
from . import special_widget_model
from . import tag_by_all_widget_model
from . import tag_by_class_widget_model
from . import textbox_widget_model
from . import user_widget_model