from . import file_upload
from . import file_upload_list
from . import fileImg_upload
from . import html_input
from . import img_upload
from . import img_upload_list
from . import multiline_input
from . import number_input
from . import simple_input